language: node_js
node_js:
  - "stable"

services:
  -postgresql

env:
  -PORT:'8080'
  -TRAVIS:true

before_script:
  - psql -c 'create database stockduel;' -U postgres
  - npm install -g npm@'2.13.0'
  - npm run dbup
