language: node_js
node_js:
  - "stable"

services:
  -postgresql

env:
  -PORT:'8080'
  -TRAVIS:true
  -CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - psql -c 'create database stockduel;' -U postgres
  - npm run dbup
